version: 0.2

env:
  secrets-manager:
    HOST: prod/sonar1:HOST
    LOGIN: prod/sonar1:sonartoken
    Project: prod/sonar1:Project
    
 
phases:
  install:
    runtime-versions:
      nodejs: 10
      java: corretto8
      
  pre_build:
     commands:
    
     - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
     - pwd
     - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
     - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
     
  build:
    commands:
      - echo Build started on `date`
      - result = $(/opt/sonar-scanner/bin/sonar-scanner -Dsonar.sourceEncoding=UTF-8- Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project)
      - echo $result
      - zip hello.zip ./index.html ./aws.gif ./1.png ./back.jpg
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
